#pragma once

#define VERSION_MAJOR 3
#define VERSION_MINOR 2
#define VERSION_PATCH 0
#define VERSION_BUILD_COUNT 0

#define STR1(x) #x
#define STR(x) STR1(x)

#define FILE_VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH) "." STR(VERSION_BUILD_COUNT)
#define PRODUCT_VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH)

#define HEXEDIT_VERSION_MAJOR VERSION_MAJOR
#define HEXEDIT_VERSION_MINOR VERSION_MINOR
#define HEXEDIT_VERSION_PATCH VERSION_PATCH
#define HEXEDIT_VERSION_BUILD_COUNT VERSION_BUILD_COUNT
#define HEXEDIT_FILE_VERSION_STRING FILE_VERSION_STRING
#define HEXEDIT_PRODUCT_VERSION_STRING PRODUCT_VERSION_STRING

#define ORG_NAME "catch22"
